//RECIPE FORM ACTIONS
export const MEDIA_CHANGE = "MEDIA_CHANGE";
export const RECIPE_NAME_CHANGE = "RECIPE_NAME_CHANGE";
export const SERVINGS_CHANGE = "SERVINGS_CHANGE";
export const INGREDIENTS_CHANGE = "INGREDIENTS_CHANGE";
export const INSTRUCTIONS_CHANGE = "INSTRUCTIONS_CHANGE";
export const TOTAL_TIME_CHANGE = "TOTAL_TIME_CHANGE";
export const KEYWORDS_CHANGE = "KEYWORDS_CHANGE";
export const CATEGORIES_CHANGE = "CATEGORIES_CHANGE";

//USER ACTIONS
export const GET_USER = "GET_USER";
export const USERNAME_CHANGE = "USERNAME_CHANGE";
export const FULLNAME_CHANGE = "FULLNAME_CHANGE";

//USER PROFILE ACTIONS - viewing another users profile
export const GET_USER_PROFILE = "GET_USER_PROFILE";

//AUTH ACTIONS
export const LOGIN_REQEUST = "LOGIN_REQEUST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOING_FAILURE = "LOING_FAILURE";
export const LOGOUT = "LOGOUT";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

//LOGIN ACTIONS
export const LOGIN_USERNAME_CHANGE = "LOGIN_USERNAME_CHANGE";
export const LOGIN_USERNAME_ERROR = "LOGIN_USERNAME_ERROR";
export const LOGIN_PASSWORD_CHANGE = "LOGIN_PASSWORD_CHANGE";
export const LOGIN_PASSWORD_ERROR = "LOGIN_PASSWORD_ERROR";

//SINGUP ACTIONS
export const SIGNUP_EMAIL_CHANGE = "SIGNUP_EMAIL_CHANGE";
export const SIGNUP_EMAIL_ERROR = "SIGNUP_EMAIL_ERROR";
export const SIGNUP_USERNAME_CHANGE = "SIGNUP_USERNAME_CHANGE";
export const SIGNUP_USERNAME_ERROR = "SIGNUP_USERNAME_ERROR";
export const SIGNUP_PASSWORD_CHANGE = "SIGNUP_PASSWORD_CHANGE";
export const SIGNUP_PASSWORD_ERROR = "SIGNUP_PASSWORD_ERROR";
