//RECIPE FORM ACTIONS
export const MEDIA_CHANGE = "MEDIA_CHANGE";
export const RECIPE_NAME_CHANGE = "RECIPE_NAME_CHANGE";
export const SERVINGS_CHANGE = "SERVINGS_CHANGE";
export const INGREDIENTS_CHANGE = "INGREDIENTS_CHANGE";
export const INSTRUCTIONS_CHANGE = "INSTRUCTIONS_CHANGE";
export const TOTAL_TIME_CHANGE = "TOTAL_TIME_CHANGE";
export const KEYWORDS_CHANGE = "KEYWORDS_CHANGE";
export const CATEGORIES_CHANGE = "CATEGORIES_CHANGE";
export const SUBMIT_RECIPE_REQUEST = "SUBMIT_RECIPE_REQUEST";
export const SUBMIT_RECIPE_SUCCESS = "SUBMIT_RECIPE_SUCCESS";
export const SUBMIT_RECIPE_FAILURE = "SUBMIT_RECIPE_FAILURE";

//USER ACTIONS
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

//USER FORM ACTIONS
export const GET_USER_STATE = "GET_USER_STATE";
export const USERNAME_CHANGE = "USERNAME_CHANGE";
export const USERNAME_ERROR = "USERNAME_ERROR";
export const FULLNAME_CHANGE = "FULLNAME_CHANGE";
export const RESTRICTION_CHANGE = "RESTRICTION_CHANGE";
export const IMAGE_URL_CHANGE = "IMAGE_URL_CHANGE";
export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

//USER PROFILE ACTIONS - viewing another users profile
export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

//AUTH ACTIONS
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOING_FAILURE = "LOING_FAILURE";
export const LOGOUT = "LOGOUT";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

//LOGIN ACTIONS
export const LOGIN_USERNAME_CHANGE = "LOGIN_USERNAME_CHANGE";
export const LOGIN_USERNAME_ERROR = "LOGIN_USERNAME_ERROR";
export const LOGIN_PASSWORD_CHANGE = "LOGIN_PASSWORD_CHANGE";
export const LOGIN_PASSWORD_ERROR = "LOGIN_PASSWORD_ERROR";

//SINGUP ACTIONS
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_EMAIL_CHANGE = "SIGNUP_EMAIL_CHANGE";
export const SIGNUP_EMAIL_ERROR = "SIGNUP_EMAIL_ERROR";
export const SIGNUP_USERNAME_CHANGE = "SIGNUP_USERNAME_CHANGE";
export const SIGNUP_USERNAME_ERROR = "SIGNUP_USERNAME_ERROR";
export const SIGNUP_PASSWORD_CHANGE = "SIGNUP_PASSWORD_CHANGE";
export const SIGNUP_PASSWORD_ERROR = "SIGNUP_PASSWORD_ERROR";
